version: '2'

services:
  back:
    extends:
      file: docker-compose.common.yml
      service: back
    volumes:
      - ./back:/var/www
    ports:
      - 8000:8000
      - 8080:8080
    environment:
      - SYMFONY_ENV=dev
      - SYMFONY_DEBUG=1
  front:
    extends:
      file: docker-compose.common.yml
      service: front
    volumes:
      - ./front:/var/www
    ports:
      - 80:80
      - 3000:3000
  mysql:
    extends:
      file: docker-compose.common.yml
      service: mysql
    ports:
      - 3306:3306
