version: '2'

services:
  back:
    extends:
      file: docker-compose.common.yml
      service: back
    volumes:
      - ./back:/var/www
    ports:
      - 8000:80
    environment:
      - SYMFONY_ENV=dev
      - SYMFONY_DEBUG=1
  front:
    extends:
      file: docker-compose.common.yml
      service: front
    volumes:
      - ./front:/var/www
    ports:
      - 3001:80
  mysql:
    extends:
      file: docker-compose.common.yml
      service: mysql
    ports:
      - 3306:3306
