version: '2'

services:
  back:
    build: ./docker/back
  front:
    build: ./docker/front
  mysql:
    build: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
